sudo: required
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

branches:
  only:
  - master

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo run ashpaper-bin/poems/lovely-poem.eso
